# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.DateField()),
                ('publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('program_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='alumni_prof',
            name='programs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Programs'),
        ),
    ]
